export declare function d<T>(input: T | undefined): T;
export declare function i<T, R>(i: T | undefined, fn: ($: T) => R): R;
export declare function assertString<T>(input: T | undefined): T;
export declare function formatBigInt(value: number): string;
export declare function timeDifferenceStr(current: number, previous: number): string;
export declare function ucfirst(text: string): string;
export declare function uniqueId(): string;
export declare function isEqualWithFunctions(o1: any, o2: any): boolean;
export declare function errToStr<T>(fn: () => T): T | string;
export declare function nestValidate(fn: () => void): boolean | string;
